logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO          # Only show executed SQL
    org.springframework.security: INFO   # Hide TRACE/DEBUG from Spring Security
    com.lnr.ecom: DEBUG              # Still see your appâ€™s debug logs
    org.apache.hc.client5.http: INFO
  file:
    name: logs/app.log   # File where logs will be stored
spring:
  docker:
    compose:
      enabled: false
  config:
    import: optional:file:.env[.properties]
  application:
    name: Ecommerce Backend
#  docker:
#      compose:
#        enabled: false


  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://dpg-d4ei2475r7bs73fq2f6g-a:5432/ecommerce_5uac
    username: admin
    password: Dhr8WkRLM4sFhRjJbr5JZwSrUQDss1ST
    hikari:
      poolName: Hikari
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        default_schema: public
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.xml
    default-schema: public
    contexts: dev
  #    drop-first: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lnreddy.kinde.com
          jwk-set-uri: https://lnreddy.kinde.com/.well-known/jwks

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: ${PORT:7878}

application:
  client-base-url: https://ecommercefullstackapplication-frontend.onrender.com
  cors:
    allowed-origins:
    - https://ecommercefullstackapplication-frontend.onrender.com
    - http://localhost:4200
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: false
    max-age: 300
  kinde:
    api: https://lnreddy.kinde.com
    client-id: ${KINDE_CLIENT_ID}
    client-secret: ${KINDE_CLIENT_SECRET}
    audience: https://lnreddy.kinde.com/api


Razorpay-Key: ${RAZORPAY_KEY}

Razorpay-Value: ${RAZORPAY_VALUE}

client-base-url: https://ecommercefullstackapplication-frontend.onrender.com
